services:
  url-shortener-api:
    build: .
    container_name: url-shortener-api
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - url-shortener-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - url-shortener-network

volumes:
  url-shortener-data:
    driver: local

networks:
  url-shortener-network:
    driver: bridge 