server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: url-shortener-api
  
  # H2 Database Configuration - File-based for persistence
  datasource:
    url: jdbc:h2:file:./data/urlshortener
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Jackson configuration for JSON handling
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Logging configuration
logging:
  level:
    com.example.urlshortener: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 