# Docker-specific configuration
server:
  port: 8080

spring:
  application:
    name: url-shortener-api
  
  # H2 Database Configuration for Docker - File-based for persistence
  datasource:
    url: jdbc:h2:file:./data/urlshortener
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Optimized for container environment
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Logging configuration for containers
logging:
  level:
    com.example.urlshortener: INFO
    org.springframework.web: INFO
    org.springframework.boot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator configuration for containers
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true 